### PR TITLE
Adds a cache also performance and readability fixes.

### PR DESCRIPTION
**Pull request by tuxxy**
Just a few logical changes to make things more efficient and more readable.

### CODE REVIEW

**Comment by tuxxy** [comment]
Closing this pull request to change core logic to add a cache from Reddit user /u/brwbck.

**Comment by tuxxy** [comment]
My github mistakes...

**Comment by tuxxy** [comment]
Okay, so this patch adds caching from /u/brwbck on reddit.

When it encounters an IP that has already been requested, it adds it to the `coord_list` without calling the API.

**Comment by jalgroy** [comment]
Awesome, great changes. Merging.

**Pull request merged**
