### PR TITLE
getlocation simplifications

### PR DESCRIPTION
**Pull request by Lucretiel**
- Now uses lru_cache for ip caching
- Now uses stdin and stdout rather than fixed filenames. Can be used in a pipeline
- Now respects `__name__ == "__main__"`
- Now uses print instead of write

### CODE REVIEW

**Comment by jalgroy** [comment]
Hi, thanks, good changes. Couple of things:
- You removed the definition of ip_lookup, while still referring to it.
- The syntax seem to only work in python 3. Specifically the `file=stderr` on line 8 gives a syntax error in 2.7.6. Is there a simple way to make this work in both 2.7 as well as in python 3.x?

**Comment by tuxxy** [comment]
I like the idea of writing to stdout, but I think these changes would be better off in a future release where there is a CLI argument for it rather than changing the entirety of the program logic.

Just my two cents.

**Comment by Lucretiel** [comment]
Making it write to stdout is just much much simpler... you don't have to worry about opening or closing a file, or even reading a filename. All those things can be done on the shell:

```
./getlocations.py < ips.txt > geo.txt
```

And now the whole map generation process can be a single command:

```
grep "refused" /var/log/auth.log | awk '{ print $9 }' | sort | uniq | ./getlocations.py | ./generatemap.py
```

**Comment by Lucretiel** [comment]
Restored support for filenames. In addition to the standard `>` `<` shell redirection operators, you can now do:

```
./getlocations.py -i ips.txt -o geo.txt API_KEY
```

You also now supply the API key on the command line as a positional parameter.

**Comment by tuxxy** [comment]
I like these changes. :+1:

**Comment by tuxxy** [comment]
When I test these changes, I'm getting some performance issues after timing:
EXECUTION TIME:   5.56885814667
EXECUTION TIME:   7.55780410767
EXECUTION TIME:   5.16170883179
EXECUTION TIME:   5.23908686638
(Run on Python 2.7.9)
With a list of four IP addresses:
166.70.88.62
1.2.3.4
8.8.8.8
1.2.3.4

Not sure how it compares to the current master quite yet.

**Comment by Lucretiel** [comment]
Let me know how it is against the master. Most of the time is going to be in the round trip to the geoip service, so I can't imagine my changes having a huge effect on performance.

**Comment by tuxxy** [comment]
I'm away from my computer at the moment, but this was on a 10Gbps
connection at my workplace.

**Comment by Lucretiel** [comment]
The latency would be 100% from the server doing work. It doesn't matter how fast the connection is, because there isn't a huge amount of data being transferred per-request. It's all in how long it takes to establish the individual connections and for the server to respond to requests. Probably the easiest way to improve the performance here would be to find out if the `ip_lookup` service can let you request multiple ips in a single request.

**Comment by tuxxy** [comment]
EXECUTION TIME:     0.5986757278442383
EXECUTION TIME:     0.5897502899169922
EXECUTION TIME:     0.5661451816558838
EXECUTION TIME:     0.702322244644165

Latency on my workplace is around 4-8ms

This was done on my home network.

**Comment by tuxxy** [comment]
I'm attempting to run the pull with Python 3.4.3 and I get this traceback:

```
Traceback (most recent call last):
  File "getlocation.py", line 54, in <module>
    main()
  File "getlocation.py", line 47, in main
    with smart_open(args.input) as istr:
  File "/usr/lib64/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "getlocation.py", line 32, in smart_open
    if isinstance(file_or_filename, (int, str, unicode, bytes)):
NameError: name 'unicode' is not defined
```

**Comment by Lucretiel** [comment]
Fixed the traceback. Are the new performance numbers on master or my patch? I literally can't imagine how any of my changed would cause a full order of magnitude difference.

**Comment by tuxxy** [comment]
I just got these numbers:
EXECUTION TIME: 6.3282954936
EXECUTION TIME: 4.33694758261

(EDIT: Pasted a bad number, fixed it though)

Then, I get these:
EXECUTION TIME: 0.54092187993
EXECUTION TIME: 0.8320334121

Strange that I got such high numbers earlier consistently and now I'm getting a mix.
Is this coincidence or is the API being weird?

I would be completely confused as to why your code would have a performance problem like this.

Also, I'd prefer to keep both Python 2 and 3 compatible.

**Comment by tuxxy** [comment]
Now, I'm getting a solid mix of high and low numbers.

I don't know what to attribute this to, but I think it might be API limitations or something.
I'll go ahead and merge it if you can add python 2 compatibility. :)

**Pull request merged**
